"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.listCategory = exports.listProducts = void 0;
// export this function
exports.listProducts = [
    {
        id: 1,
        name: "tomato",
        pricePerKg: "£ 1.3",
        type: 2,
        img: "https://images.unsplash.com/photo-1517666005606-69dea9b54865?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=876&q=80",
    },
    {
        id: 1783,
        name: "lettuce",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/vegetable4.jpg?raw=true",
        type: 2,
        pricePerKg: "£ 0.30",
    },
    {
        id: 2,
        name: "carrot",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/vegetable3.jpg?raw=true",
        type: 2,
        pricePerKg: "£ 1.3",
    },
    {
        id: 100,
        name: "cauliflower",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/vegetable2.jpg?raw=true",
        type: 2,
        pricePerKg: "£ 0.58",
    },
    {
        id: 3,
        name: "cucumber",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/vegetable5.jpg?raw=true",
        type: 2,
        pricePerKg: "£ 1.5",
    },
    {
        id: 4,
        name: "pumpkin",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/vegetable1.jpg?raw=true",
        type: 2,
        pricePerKg: "£ 0.6",
    },
    {
        id: 5,
        name: "red pepper",
        img: "https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjB8fGZydWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 2,
        pricePerKg: "£ 1.6",
    },
    {
        id: 7,
        name: "Pineapple",
        img: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJ1aXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        type: 1,
        pricePerKg: "£ 7.1",
    },
    {
        id: 8,
        name: "Banana",
        img: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzJ8fGZydWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 1,
        pricePerKg: "£ 2.50",
    },
    {
        id: 9,
        name: "Cherry",
        img: "https://images.unsplash.com/photo-1457296898342-cdd24585d095?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fGZydWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 1,
        pricePerKg: "£ 4.2",
    },
    {
        id: 10,
        name: "Apple",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/fruit2.jpg?raw=true",
        type: 1,
        pricePerKg: "£ 2.4",
    },
    {
        id: 11,
        name: "Raspberries",
        img: "https://images.unsplash.com/photo-1577069861033-55d04cec4ef5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDd8fGZydWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 1,
        pricePerKg: "£ 4.33",
    },
    {
        id: 12,
        name: "Oranges",
        img: "https://images.unsplash.com/photo-1547514701-42782101795e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGZydWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 1,
        pricePerKg: "£ 1.44",
    },
    {
        id: 13,
        name: "Chicken Leg",
        img: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fENoaWNrZW58ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        type: 3,
        pricePerKg: "£ 20.99",
    },
    {
        id: 14,
        name: "thighs chicken",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/chicken.jpg?raw=true",
        type: 3,
        pricePerKg: "£ 10.44",
    },
    {
        id: 15,
        name: "Frozen Chicken Leg Boneless",
        img: "https://images.unsplash.com/photo-1501200291289-c5a76c232e5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8RnJvemVuJTIwQ2hpY2tlbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=400&q=60",
        type: 3,
        pricePerKg: "£ 15.44",
    },
    {
        id: 16,
        name: "Frozen Chicken",
        img: "https://images.unsplash.com/photo-1605002619349-82dce91bcee0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDB8fGJyZWFkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 3,
        pricePerKg: "£ 25.3",
    },
    {
        id: 17,
        name: "Challah",
        img: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/bread1.jpg?raw=true",
        type: 4,
        pricePerKg: "£ 2",
    },
    {
        id: 18,
        name: "Rye Bread",
        img: "https://images.unsplash.com/photo-1588861472194-6883d8b5e552?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzV8fGJyZWFkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 4,
        pricePerKg: "£ 0.3",
    },
    {
        id: 19,
        name: " Sourdough Bread",
        img: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YnJlYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        type: 4,
        pricePerKg: "£ 3",
    },
    {
        id: 20,
        name: "Pumpkin Bread",
        img: "https://images.unsplash.com/photo-1559811814-e2c57b5e69df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGJyZWFkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        type: 4,
        pricePerKg: "£ 0.6",
    },
];
exports.listCategory = [
    {
        id: "1",
        name: "F",
        image: "https://i.ibb.co/7bQQYkX/tomato.png",
    },
    {
        id: "2",
        name: "Vegetable",
        image: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/List2.png?raw=true",
    },
    {
        id: "3",
        name: "chicken ",
        image: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/List3.png?raw=true",
    },
    {
        id: "4",
        name: "bread ",
        image: "https://github.com/fahad0samara/Full.stack-RactNative-gold-app/blob/master/assets/List4.png?raw=true",
    },
];
